version: "3"

# Please copy config/config.example.yaml to config/config.yaml and fill in the variables
# and copy config/wechat-bot.memory-card.example.json to config/wechat-bot.memory-card.json

services:
    wechat-bot:
        # image: darknightlab/wechat-bot:main
        image: ghcr.io/darknightlab/wechat-bot:main
        # build: .
        container_name: wechat-bot
        restart: always
        init: true
        environment:
            - WECHATY_LOG=verbose
        volumes:
            - ./config:/wechat-bot/config
networks:
    wechat-bot:
        name: wechat-bot
        driver: bridge
        enable_ipv6: true
