version: "3"

# Please copy config/config.example.yaml to config/config.yaml and fill in the variables
# and copy config/wechat-bot.memory-card.example.json to config/wechat-bot.memory-card.json

services:
    wechat-bot:
        image: darknightlab/wechat-bot:latest
        # image: ghcr.io/darknightlab/wechat-bot:main
        # build: .
        container_name: wechat-bot
        restart: always
        # init: true # 似乎曾经在用浏览器方法时具有特殊意义
        environment:
            - WECHATY_LOG=INFO
        volumes:
            - ./config:/wechat-bot/config
networks:
    wechat-bot:
        name: wechat-bot
        driver: bridge
        enable_ipv6: true
